// This file is @generated by prost-build.
/// QueryRemainderRequest defines the request type for Query/Remainder method.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryRemainderRequest {}
impl ::prost::Name for QueryRemainderRequest {
    const NAME: &'static str = "QueryRemainderRequest";
    const PACKAGE: &'static str = "cosmos.evm.precisebank.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.evm.precisebank.v1.QueryRemainderRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.evm.precisebank.v1.QueryRemainderRequest".into()
    }
}
/// QueryRemainderResponse defines the response type for Query/Remainder method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRemainderResponse {
    /// remainder is the amount backed by the reserve, but not yet owned by any
    /// account, i.e. not in circulation.
    #[prost(message, optional, tag = "1")]
    pub remainder: ::core::option::Option<
        ::cosmos_sdk_proto::cosmos::base::v1beta1::Coin,
    >,
}
impl ::prost::Name for QueryRemainderResponse {
    const NAME: &'static str = "QueryRemainderResponse";
    const PACKAGE: &'static str = "cosmos.evm.precisebank.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.evm.precisebank.v1.QueryRemainderResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.evm.precisebank.v1.QueryRemainderResponse".into()
    }
}
/// QueryFractionalBalanceRequest defines the request type for
/// Query/FractionalBalance method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryFractionalBalanceRequest {
    /// address is the account address to query  fractional balance for.
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
}
impl ::prost::Name for QueryFractionalBalanceRequest {
    const NAME: &'static str = "QueryFractionalBalanceRequest";
    const PACKAGE: &'static str = "cosmos.evm.precisebank.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.evm.precisebank.v1.QueryFractionalBalanceRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.evm.precisebank.v1.QueryFractionalBalanceRequest".into()
    }
}
/// QueryFractionalBalanceResponse defines the response type for
/// Query/FractionalBalance method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryFractionalBalanceResponse {
    /// fractional_balance is the fractional balance of the address.
    #[prost(message, optional, tag = "1")]
    pub fractional_balance: ::core::option::Option<
        ::cosmos_sdk_proto::cosmos::base::v1beta1::Coin,
    >,
}
impl ::prost::Name for QueryFractionalBalanceResponse {
    const NAME: &'static str = "QueryFractionalBalanceResponse";
    const PACKAGE: &'static str = "cosmos.evm.precisebank.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.evm.precisebank.v1.QueryFractionalBalanceResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.evm.precisebank.v1.QueryFractionalBalanceResponse".into()
    }
}
/// Generated client implementations.
#[cfg(feature = "client")]
pub mod query_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Query defines the gRPC querier service for precisebank module
    #[derive(Debug, Clone)]
    pub struct QueryClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    #[cfg(feature = "transport")]
    impl QueryClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> QueryClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> QueryClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            QueryClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Remainder returns the amount backed by the reserve, but not yet owned by
        /// any account, i.e. not in circulation.
        pub async fn remainder(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryRemainderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryRemainderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.evm.precisebank.v1.Query/Remainder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cosmos.evm.precisebank.v1.Query", "Remainder"));
            self.inner.unary(req, path, codec).await
        }
        /// FractionalBalance returns only the fractional balance of an address. This
        /// does not include any integer balance.
        pub async fn fractional_balance(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryFractionalBalanceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryFractionalBalanceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.evm.precisebank.v1.Query/FractionalBalance",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cosmos.evm.precisebank.v1.Query",
                        "FractionalBalance",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
#[cfg(feature = "server")]
pub mod query_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with QueryServer.
    #[async_trait]
    pub trait Query: std::marker::Send + std::marker::Sync + 'static {
        /// Remainder returns the amount backed by the reserve, but not yet owned by
        /// any account, i.e. not in circulation.
        async fn remainder(
            &self,
            request: tonic::Request<super::QueryRemainderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryRemainderResponse>,
            tonic::Status,
        >;
        /// FractionalBalance returns only the fractional balance of an address. This
        /// does not include any integer balance.
        async fn fractional_balance(
            &self,
            request: tonic::Request<super::QueryFractionalBalanceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryFractionalBalanceResponse>,
            tonic::Status,
        >;
    }
    /// Query defines the gRPC querier service for precisebank module
    #[derive(Debug)]
    pub struct QueryServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> QueryServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for QueryServer<T>
    where
        T: Query,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cosmos.evm.precisebank.v1.Query/Remainder" => {
                    #[allow(non_camel_case_types)]
                    struct RemainderSvc<T: Query>(pub Arc<T>);
                    impl<
                        T: Query,
                    > tonic::server::UnaryService<super::QueryRemainderRequest>
                    for RemainderSvc<T> {
                        type Response = super::QueryRemainderResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QueryRemainderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Query>::remainder(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RemainderSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cosmos.evm.precisebank.v1.Query/FractionalBalance" => {
                    #[allow(non_camel_case_types)]
                    struct FractionalBalanceSvc<T: Query>(pub Arc<T>);
                    impl<
                        T: Query,
                    > tonic::server::UnaryService<super::QueryFractionalBalanceRequest>
                    for FractionalBalanceSvc<T> {
                        type Response = super::QueryFractionalBalanceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QueryFractionalBalanceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Query>::fractional_balance(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FractionalBalanceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for QueryServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cosmos.evm.precisebank.v1.Query";
    impl<T> tonic::server::NamedService for QueryServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// GenesisState defines the precisebank module's genesis state.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenesisState {
    /// balances is a list of all the balances in the precisebank module.
    #[prost(message, repeated, tag = "1")]
    pub balances: ::prost::alloc::vec::Vec<FractionalBalance>,
    /// remainder is an internal value of how much extra fractional digits are
    /// still backed by the reserve, but not assigned to any account.
    #[prost(string, tag = "2")]
    pub remainder: ::prost::alloc::string::String,
}
impl ::prost::Name for GenesisState {
    const NAME: &'static str = "GenesisState";
    const PACKAGE: &'static str = "cosmos.evm.precisebank.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.evm.precisebank.v1.GenesisState".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.evm.precisebank.v1.GenesisState".into()
    }
}
/// FractionalBalance defines the fractional portion of an account balance
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FractionalBalance {
    /// address is the address of the balance holder.
    #[prost(string, tag = "1")]
    pub address: ::prost::alloc::string::String,
    /// amount indicates amount of only the fractional balance owned by the
    /// address. FractionalBalance currently only supports tracking 1 single asset,
    /// e.g. fractional balances of uatom.
    #[prost(string, tag = "2")]
    pub amount: ::prost::alloc::string::String,
}
impl ::prost::Name for FractionalBalance {
    const NAME: &'static str = "FractionalBalance";
    const PACKAGE: &'static str = "cosmos.evm.precisebank.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.evm.precisebank.v1.FractionalBalance".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.evm.precisebank.v1.FractionalBalance".into()
    }
}
