// This file is @generated by prost-build.
/// Module is the config object of the epochs module.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Module {}
impl ::prost::Name for Module {
    const NAME: &'static str = "Module";
    const PACKAGE: &'static str = "cosmos.epochs.module.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.epochs.module.v1.Module".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.epochs.module.v1.Module".into()
    }
}
