// This file is @generated by prost-build.
/// BaseVestingAccount implements the VestingAccount interface. It contains all
/// the necessary fields needed for any vesting account implementation.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BaseVestingAccount {
    #[prost(message, optional, tag = "1")]
    pub base_account: ::core::option::Option<super::super::auth::v1beta1::BaseAccount>,
    #[prost(message, repeated, tag = "2")]
    pub original_vesting: ::prost::alloc::vec::Vec<
        ::cosmos_sdk_proto::cosmos::base::v1beta1::Coin,
    >,
    #[prost(message, repeated, tag = "3")]
    pub delegated_free: ::prost::alloc::vec::Vec<
        ::cosmos_sdk_proto::cosmos::base::v1beta1::Coin,
    >,
    #[prost(message, repeated, tag = "4")]
    pub delegated_vesting: ::prost::alloc::vec::Vec<
        ::cosmos_sdk_proto::cosmos::base::v1beta1::Coin,
    >,
    /// Vesting end time, as unix timestamp (in seconds).
    #[prost(int64, tag = "5")]
    pub end_time: i64,
}
impl ::prost::Name for BaseVestingAccount {
    const NAME: &'static str = "BaseVestingAccount";
    const PACKAGE: &'static str = "cosmos.vesting.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.vesting.v1beta1.BaseVestingAccount".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.vesting.v1beta1.BaseVestingAccount".into()
    }
}
/// ContinuousVestingAccount implements the VestingAccount interface. It
/// continuously vests by unlocking coins linearly with respect to time.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContinuousVestingAccount {
    #[prost(message, optional, tag = "1")]
    pub base_vesting_account: ::core::option::Option<BaseVestingAccount>,
    /// Vesting start time, as unix timestamp (in seconds).
    #[prost(int64, tag = "2")]
    pub start_time: i64,
}
impl ::prost::Name for ContinuousVestingAccount {
    const NAME: &'static str = "ContinuousVestingAccount";
    const PACKAGE: &'static str = "cosmos.vesting.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.vesting.v1beta1.ContinuousVestingAccount".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.vesting.v1beta1.ContinuousVestingAccount".into()
    }
}
/// DelayedVestingAccount implements the VestingAccount interface. It vests all
/// coins after a specific time, but non prior. In other words, it keeps them
/// locked until a specified time.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DelayedVestingAccount {
    #[prost(message, optional, tag = "1")]
    pub base_vesting_account: ::core::option::Option<BaseVestingAccount>,
}
impl ::prost::Name for DelayedVestingAccount {
    const NAME: &'static str = "DelayedVestingAccount";
    const PACKAGE: &'static str = "cosmos.vesting.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.vesting.v1beta1.DelayedVestingAccount".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.vesting.v1beta1.DelayedVestingAccount".into()
    }
}
/// Period defines a length of time and amount of coins that will vest.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Period {
    /// Period duration in seconds.
    #[prost(int64, tag = "1")]
    pub length: i64,
    #[prost(message, repeated, tag = "2")]
    pub amount: ::prost::alloc::vec::Vec<
        ::cosmos_sdk_proto::cosmos::base::v1beta1::Coin,
    >,
}
impl ::prost::Name for Period {
    const NAME: &'static str = "Period";
    const PACKAGE: &'static str = "cosmos.vesting.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.vesting.v1beta1.Period".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.vesting.v1beta1.Period".into()
    }
}
/// PeriodicVestingAccount implements the VestingAccount interface. It
/// periodically vests by unlocking coins during each specified period.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeriodicVestingAccount {
    #[prost(message, optional, tag = "1")]
    pub base_vesting_account: ::core::option::Option<BaseVestingAccount>,
    #[prost(int64, tag = "2")]
    pub start_time: i64,
    #[prost(message, repeated, tag = "3")]
    pub vesting_periods: ::prost::alloc::vec::Vec<Period>,
}
impl ::prost::Name for PeriodicVestingAccount {
    const NAME: &'static str = "PeriodicVestingAccount";
    const PACKAGE: &'static str = "cosmos.vesting.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.vesting.v1beta1.PeriodicVestingAccount".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.vesting.v1beta1.PeriodicVestingAccount".into()
    }
}
/// PermanentLockedAccount implements the VestingAccount interface. It does
/// not ever release coins, locking them indefinitely. Coins in this account can
/// still be used for delegating and for governance votes even while locked.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PermanentLockedAccount {
    #[prost(message, optional, tag = "1")]
    pub base_vesting_account: ::core::option::Option<BaseVestingAccount>,
}
impl ::prost::Name for PermanentLockedAccount {
    const NAME: &'static str = "PermanentLockedAccount";
    const PACKAGE: &'static str = "cosmos.vesting.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.vesting.v1beta1.PermanentLockedAccount".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.vesting.v1beta1.PermanentLockedAccount".into()
    }
}
/// MsgCreateVestingAccount defines a message that enables creating a vesting
/// account.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreateVestingAccount {
    #[prost(string, tag = "1")]
    pub from_address: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub to_address: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub amount: ::prost::alloc::vec::Vec<
        ::cosmos_sdk_proto::cosmos::base::v1beta1::Coin,
    >,
    /// end of vesting as unix time (in seconds).
    #[prost(int64, tag = "4")]
    pub end_time: i64,
    #[prost(bool, tag = "5")]
    pub delayed: bool,
}
impl ::prost::Name for MsgCreateVestingAccount {
    const NAME: &'static str = "MsgCreateVestingAccount";
    const PACKAGE: &'static str = "cosmos.vesting.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.vesting.v1beta1.MsgCreateVestingAccount".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.vesting.v1beta1.MsgCreateVestingAccount".into()
    }
}
/// MsgCreateVestingAccountResponse defines the Msg/CreateVestingAccount response type.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgCreateVestingAccountResponse {}
impl ::prost::Name for MsgCreateVestingAccountResponse {
    const NAME: &'static str = "MsgCreateVestingAccountResponse";
    const PACKAGE: &'static str = "cosmos.vesting.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.vesting.v1beta1.MsgCreateVestingAccountResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.vesting.v1beta1.MsgCreateVestingAccountResponse".into()
    }
}
/// MsgCreatePermanentLockedAccount defines a message that enables creating a permanent
/// locked account.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreatePermanentLockedAccount {
    #[prost(string, tag = "1")]
    pub from_address: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub to_address: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub amount: ::prost::alloc::vec::Vec<
        ::cosmos_sdk_proto::cosmos::base::v1beta1::Coin,
    >,
}
impl ::prost::Name for MsgCreatePermanentLockedAccount {
    const NAME: &'static str = "MsgCreatePermanentLockedAccount";
    const PACKAGE: &'static str = "cosmos.vesting.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.vesting.v1beta1.MsgCreatePermanentLockedAccount".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.vesting.v1beta1.MsgCreatePermanentLockedAccount".into()
    }
}
/// MsgCreatePermanentLockedAccountResponse defines the Msg/CreatePermanentLockedAccount response type.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgCreatePermanentLockedAccountResponse {}
impl ::prost::Name for MsgCreatePermanentLockedAccountResponse {
    const NAME: &'static str = "MsgCreatePermanentLockedAccountResponse";
    const PACKAGE: &'static str = "cosmos.vesting.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.vesting.v1beta1.MsgCreatePermanentLockedAccountResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.vesting.v1beta1.MsgCreatePermanentLockedAccountResponse".into()
    }
}
/// MsgCreateVestingAccount defines a message that enables creating a vesting
/// account.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgCreatePeriodicVestingAccount {
    #[prost(string, tag = "1")]
    pub from_address: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub to_address: ::prost::alloc::string::String,
    /// start of vesting as unix time (in seconds).
    #[prost(int64, tag = "3")]
    pub start_time: i64,
    #[prost(message, repeated, tag = "4")]
    pub vesting_periods: ::prost::alloc::vec::Vec<Period>,
}
impl ::prost::Name for MsgCreatePeriodicVestingAccount {
    const NAME: &'static str = "MsgCreatePeriodicVestingAccount";
    const PACKAGE: &'static str = "cosmos.vesting.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.vesting.v1beta1.MsgCreatePeriodicVestingAccount".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.vesting.v1beta1.MsgCreatePeriodicVestingAccount".into()
    }
}
/// MsgCreateVestingAccountResponse defines the Msg/CreatePeriodicVestingAccount
/// response type.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgCreatePeriodicVestingAccountResponse {}
impl ::prost::Name for MsgCreatePeriodicVestingAccountResponse {
    const NAME: &'static str = "MsgCreatePeriodicVestingAccountResponse";
    const PACKAGE: &'static str = "cosmos.vesting.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.vesting.v1beta1.MsgCreatePeriodicVestingAccountResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.vesting.v1beta1.MsgCreatePeriodicVestingAccountResponse".into()
    }
}
/// Generated client implementations.
#[cfg(feature = "client")]
pub mod msg_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Msg defines the bank Msg service.
    #[derive(Debug, Clone)]
    pub struct MsgClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    #[cfg(feature = "transport")]
    impl MsgClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MsgClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MsgClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MsgClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// CreateVestingAccount defines a method that enables creating a vesting
        /// account.
        pub async fn create_vesting_account(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgCreateVestingAccount>,
        ) -> std::result::Result<
            tonic::Response<super::MsgCreateVestingAccountResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.vesting.v1beta1.Msg/CreateVestingAccount",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cosmos.vesting.v1beta1.Msg", "CreateVestingAccount"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// CreatePermanentLockedAccount defines a method that enables creating a permanent
        /// locked account.
        pub async fn create_permanent_locked_account(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgCreatePermanentLockedAccount>,
        ) -> std::result::Result<
            tonic::Response<super::MsgCreatePermanentLockedAccountResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.vesting.v1beta1.Msg/CreatePermanentLockedAccount",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cosmos.vesting.v1beta1.Msg",
                        "CreatePermanentLockedAccount",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// CreatePeriodicVestingAccount defines a method that enables creating a
        /// periodic vesting account.
        pub async fn create_periodic_vesting_account(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgCreatePeriodicVestingAccount>,
        ) -> std::result::Result<
            tonic::Response<super::MsgCreatePeriodicVestingAccountResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.vesting.v1beta1.Msg/CreatePeriodicVestingAccount",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cosmos.vesting.v1beta1.Msg",
                        "CreatePeriodicVestingAccount",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
#[cfg(feature = "server")]
pub mod msg_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MsgServer.
    #[async_trait]
    pub trait Msg: std::marker::Send + std::marker::Sync + 'static {
        /// CreateVestingAccount defines a method that enables creating a vesting
        /// account.
        async fn create_vesting_account(
            &self,
            request: tonic::Request<super::MsgCreateVestingAccount>,
        ) -> std::result::Result<
            tonic::Response<super::MsgCreateVestingAccountResponse>,
            tonic::Status,
        >;
        /// CreatePermanentLockedAccount defines a method that enables creating a permanent
        /// locked account.
        async fn create_permanent_locked_account(
            &self,
            request: tonic::Request<super::MsgCreatePermanentLockedAccount>,
        ) -> std::result::Result<
            tonic::Response<super::MsgCreatePermanentLockedAccountResponse>,
            tonic::Status,
        >;
        /// CreatePeriodicVestingAccount defines a method that enables creating a
        /// periodic vesting account.
        async fn create_periodic_vesting_account(
            &self,
            request: tonic::Request<super::MsgCreatePeriodicVestingAccount>,
        ) -> std::result::Result<
            tonic::Response<super::MsgCreatePeriodicVestingAccountResponse>,
            tonic::Status,
        >;
    }
    /// Msg defines the bank Msg service.
    #[derive(Debug)]
    pub struct MsgServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MsgServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MsgServer<T>
    where
        T: Msg,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cosmos.vesting.v1beta1.Msg/CreateVestingAccount" => {
                    #[allow(non_camel_case_types)]
                    struct CreateVestingAccountSvc<T: Msg>(pub Arc<T>);
                    impl<
                        T: Msg,
                    > tonic::server::UnaryService<super::MsgCreateVestingAccount>
                    for CreateVestingAccountSvc<T> {
                        type Response = super::MsgCreateVestingAccountResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MsgCreateVestingAccount>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::create_vesting_account(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateVestingAccountSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cosmos.vesting.v1beta1.Msg/CreatePermanentLockedAccount" => {
                    #[allow(non_camel_case_types)]
                    struct CreatePermanentLockedAccountSvc<T: Msg>(pub Arc<T>);
                    impl<
                        T: Msg,
                    > tonic::server::UnaryService<super::MsgCreatePermanentLockedAccount>
                    for CreatePermanentLockedAccountSvc<T> {
                        type Response = super::MsgCreatePermanentLockedAccountResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::MsgCreatePermanentLockedAccount,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::create_permanent_locked_account(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreatePermanentLockedAccountSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cosmos.vesting.v1beta1.Msg/CreatePeriodicVestingAccount" => {
                    #[allow(non_camel_case_types)]
                    struct CreatePeriodicVestingAccountSvc<T: Msg>(pub Arc<T>);
                    impl<
                        T: Msg,
                    > tonic::server::UnaryService<super::MsgCreatePeriodicVestingAccount>
                    for CreatePeriodicVestingAccountSvc<T> {
                        type Response = super::MsgCreatePeriodicVestingAccountResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::MsgCreatePeriodicVestingAccount,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::create_periodic_vesting_account(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreatePeriodicVestingAccountSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MsgServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cosmos.vesting.v1beta1.Msg";
    impl<T> tonic::server::NamedService for MsgServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
